version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3307:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_PASSWORD=rootpwd
      - MYSQL_USER=local_user
      - MYSQL_DATABASE=spring_batch_db